-- سكربت إنشاء نسخة احتياطية للجداول الجغرافية والعملاء قبل التعديل
-- يتم إنشاء جداول جديدة مكررة تنتهي بـ _BKP كنسخة أمان

CREATE TABLE IAS20261.CITIES_BKP AS SELECT * FROM IAS20261.CITIES;
CREATE TABLE IAS20261.REGIONS_BKP AS SELECT * FROM IAS20261.REGIONS;
CREATE TABLE IAS20261.CUSTOMER_BKP AS SELECT * FROM IAS20261.CUSTOMER;
CREATE TABLE IAS20261.IAS_PROVINCES_BKP AS SELECT * FROM IAS20261.IAS_PROVINCES;

-- الجداول الأخرى المرتبطة التي سيتم تعديل رقم المحافظة فيها
CREATE TABLE IAS20261.WAREHOUSE_DETAILS_BKP AS SELECT * FROM IAS20261.WAREHOUSE_DETAILS;
CREATE TABLE IAS20261.S_BRN_BKP AS SELECT * FROM IAS20261.S_BRN;
CREATE TABLE IAS20261.IAS_SMAN_COL_CNDTN_DTL_BKP AS SELECT * FROM IAS20261.IAS_SMAN_COL_CNDTN_DTL;
CREATE TABLE IAS20261.IAS_ONLINE_CONN_WC_RGN_BKP AS SELECT * FROM IAS20261.IAS_ONLINE_CONN_WC_RGN;

-- ملاحظة: إذا احتجت لاستعادة أي جدول لاحقاً، يمكنك استخدام:
-- TRUNCATE TABLE IAS20261.CITIES;
-- INSERT INTO IAS20261.CITIES SELECT * FROM IAS20261.CITIES_BKP;
